{% set name = "trackastra" %}
{% set version = "0.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trackastra-{{ version }}.tar.gz
  sha256: e62be9b6c0a107aa1612f12a7c044e8dda996609b6459f79ae24a639fe0c8f1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - trackastra = trackastra.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy
    - pandas
    - humanize
    - configargparse
    - tensorboard
    - pyyaml
    - numba
    - scikit-image
    - chardet
    - lightning
    - kornia >=0.7.0
    - pytorch
    - torchvision
    - lz4
    - imagecodecs >=2023.7.10
    - wandb
    - edt
    - joblib
    - motile >=0.3

test:
  imports:
    - trackastra
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/weigertlab/trackastra
  summary: Tracking by Association with Transformers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bentaculum
